[project]
name = "llama-cpp-opencodereasoning-nemotron-1-1-32b"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "huggingface-hub[cli]>=0.19.0",
    "requests==2.31.0",
]
